"""User related endpoints."""

import os
import string
import random
from typing import List, Any
from datetime import datetime, timedelta, UTC
from fastapi import APIRouter, Security, Query

from .auth import get_current_user
from ...models import (
    UserOut,
    UserIn,
    User,
    UserDB,
    UserUpdate,
    UserDelete,
    TokenDelete
)
from ...utils import DBConnector, Collections, Logger


router = APIRouter()
connector = DBConnector()
logger = Logger()

SECRET_KEY = os.environ["JWT_SECRET"]
ALGORITHM = os.environ["JWT_ALGORITHM"]


@router.get("/users", description="Get list of users.", tags=["Users"])
async def get_users(
    user: User = Security(get_current_user, scopes=["admin"])
) -> List[UserOut]:
    """List users."""
    return [
        UserOut(**user)
        for user in connector.collection(Collections.USERS).find(
            {"username": {"$nin": [user.username, "admin"]}, "sso": False}
        )
    ]


@router.post(
    "/users",
    description="Create new user.",
    tags=["Users"],
    response_model=UserOut,
)
async def post_user(
    user: UserIn,
    loggedin_user: User = Security(get_current_user, scopes=["admin"]),
) -> UserOut:
    """Create user."""
    connector.collection(Collections.USERS).insert_one(
        UserDB(**user.model_dump()).model_dump()
    )
    logger.debug(
        f"User {user.username} created with {', '.join(user.scopes)} scope(s)."
    )
    return user


@router.patch(
    "/users",
    description="Update existing user.",
    tags=["Users"],
    response_model=UserOut,
)
async def patch_user(
    user: UserUpdate,
    loggedin_user: User = Security(get_current_user, scopes=["admin"]),
) -> UserOut:
    """Create user."""
    connector.collection(Collections.USERS).update_one(
        {"username": user.username},
        {"$set": {k: v for k, v in user.model_dump().items() if v is not None}},
    )
    if user.password is not None:
        logger.debug(
            f"Password updated for user {user.username} with scope(s) {', '.join(user.scopes)}."
        )
    else:
        logger.debug(
            f"User {user.username} updated with scopes(s) {', '.join(user.scopes)}."
        )
    return connector.collection(Collections.USERS).find_one(
        {"username": user.username}
    )


@router.delete("/users", description="Delete a user.", tags=["Users"])
async def delete_user(
    user: UserDelete,
    loggedin_user: User = Security(get_current_user, scopes=["admin"]),
):
    """Delete a user."""
    connector.collection(Collections.USERS).delete_one(
        {"username": user.username}
    )
    logger.debug(f"User {user.username} is deleted.")
    return {}


@router.get(
    "/users/tokens", description="List user's auth tokens.", tags=["Users"]
)
async def list_auth_tokens(
    user: User = Security(get_current_user, scopes=["me"]),
) -> Any:
    """Generate new authentication token."""
    return connector.collection(Collections.USERS).find_one(
        {"username": user.username}
    )["tokens"]


@router.post(
    "/users/tokens", description="Request a new auth token.", tags=["Users"]
)
async def create_auth_token(
    description: str = Query(..., min_length=1),
    expire_after: int = Query(60),
    user: User = Security(get_current_user, scopes=["me", "api"]),
) -> Any:
    """Generate new authentication token."""
    if expire_after >= 0:
        expires_at = datetime.now(UTC) + timedelta(minutes=expire_after)
    else:
        expires_at = None
    token = {
        "client_id": "".join(
            random.choices(string.ascii_lowercase + string.digits, k=32)
        ),
        "client_secret": "".join(
            random.choices(string.ascii_lowercase + string.digits, k=64)
        ),
        "description": description,
        "expiresAt": expires_at,
        "consecutiveFailedAttempts": 0,
        "credentialDownTime": None
    }
    # store the token for revoking in future
    connector.collection(Collections.USERS).update_one(
        {"username": user.username}, {"$push": {"tokens": token}}
    )
    logger.debug(f"New client id generated by user {user.username}.")
    return token


@router.delete(
    "/users/tokens", description="Revoke an auth token.", tags=["Users"]
)
async def delete_auth_token(
    token: TokenDelete,
    user: User = Security(get_current_user, scopes=["me"]),
) -> Any:
    """Generate new authentication token."""
    connector.collection(Collections.USERS).update_one(
        {"username": user.username},
        {"$pull": {"tokens": {"client_id": token.client_id}}},
    )
    logger.debug(
        f"An authentication token has been revoked by user {user.username}."
    )
    return {}
