"""Models for analyze endpoint."""

from typing import Optional

from pydantic import BaseModel, Field, model_validator


class AnalyzeRequest(BaseModel):
    """Incoming request for log analysis."""

    logId: Optional[str] = Field(None)

    @model_validator(mode="after")
    def _validate_input(self):
        if self.logId:
            return self
        raise ValueError("logId is required for analysis.")


class Citation(BaseModel):
    """A documentation source consulted while grounding the analysis."""

    title: str = Field(
        description="Human-readable page or section title, e.g. 'Troubleshooting the Amazon Security Lake Plugin'.",
    )
    url: str = Field(description="Full source URL.")


class AnalyzeResponse(BaseModel):
    """Normalized response for analysis result."""

    summary: str
    probableRootCause: str = Field(
        ...,
        description="The probable root cause of the log. At max top 2 possibilities.",
    )
    suggestedRemediation: str = Field(
        "",
        description="<Important Notes>"
        "1. If the suggested remediation mentions about contacting support team, "
        "mention to attach the diagnose file generated by visiting Settings > General > Run Diagnose, "
        "this would help the Support team with initial discovery."
        "2. Suggestion should never mention the exact Shell or terminal commands, we don't want the users to break "
        "their already working CE deployment."
        "3. Since the CE source code is dockerize, you must never suggest any code changes for any of the scenarios, "
        "if need be you can only redirect user to valid citation link only if available."
        "</Important Notes> ",
    )
    citations: list[Citation] = Field(
        default_factory=list,
        description="Documentation sources grounding this analysis. Do NOT inline "
        "these URLs in the prose fields — surface them only here.",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="This should never be 0, "
        "since this indicates how confident are you with the analysis of the observed data. "
        "if its 0, then it implies you have not done your due-diligence.",
    )
    inputTokens: int = Field(default=0, description="Total input tokens consumed across all LLM calls")
    outputTokens: int = Field(default=0, description="Total output tokens consumed across all LLM calls")
